webhooks:
  # Example webhook configuration (remove or replace with your own)
  # example:
  #   name: "Example Webhook"
  #   url: "https://discord.com/api/webhooks/your-webhook-url"
  #   messageTemplate: "Server message: %message%" # Optional
  #   embedTemplate: # Optional
  #     title: "Server Notification"
  #     description: "%message%"
  #     color: 0xFF0000
  #
  # Note: Discord webhooks (URLs containing discord.com or discordapp.com)
  # will automatically receive messages as embeds instead of plain text.
